const data = [
    {
      id: 1,
      tipo: 'Estágio',
      estagiario: 'João Silva',
      departamento: 'TI',
      status: 'Em andamento',
      concedente: 'Empresa XYZ',
      dataInicio: '2023-01-15',
      dataTermino: '2023-06-15',
    },
    {
      id: 2,
      tipo: 'Estágio',
      estagiario: 'Maria Oliveira',
      departamento: 'Recursos Humanos',
      status: 'Concluído',
      concedente: 'Empresa ABC',
      dataInicio: '2023-02-10',
      dataTermino: '2023-07-10',
    },
    {
      id: 3,
      tipo: 'Estágio',
      estagiario: 'Pedro Santos',
      departamento: 'Marketing',
      status: 'Em andamento',
      concedente: 'Empresa 123',
      dataInicio: '2023-03-05',
      dataTermino: '2023-08-05',
    },
    {
      id: 4,
      tipo: 'Estágio',
      estagiario: 'Ana Souza',
      departamento: 'Vendas',
      status: 'Concluído',
      concedente: 'Empresa XYZ',
      dataInicio: '2023-04-20',
      dataTermino: '2023-09-20',
    },
    {
      id: 5,
      tipo: 'Estágio',
      estagiario: 'Carlos Silva',
      departamento: 'Produção',
      status: 'Em andamento',
      concedente: 'Empresa 789',
      dataInicio: '2023-05-12',
      dataTermino: '2023-10-12',
    },
    {
      id: 6,
      tipo: 'Estágio',
      estagiario: 'Mariana Oliveira',
      departamento: 'RH',
      status: 'Concluído',
      concedente: 'Empresa XYZ',
      dataInicio: '2023-06-08',
      dataTermino: '2023-11-08',
    },
    {
      id: 7,
      tipo: 'Estágio',
      estagiario: 'Rafaela Lima',
      departamento: 'Marketing',
      status: 'Em andamento',
      concedente: 'Empresa ABC',
      dataInicio: '2023-07-25',
      dataTermino: '2023-12-25',
    },
    {
      id: 8,
      tipo: 'Estágio',
      estagiario: 'Lucas Oliveira',
      departamento: 'TI',
      status: 'Em andamento',
      concedente: 'Empresa 123',
      dataInicio: '2023-08-18',
      dataTermino: '2024-01-18',
    },
    {
      id: 9,
      tipo: 'Estágio',
      estagiario: 'Juliana Santos',
      departamento: 'Vendas',
      status: 'Concluído',
      concedente: 'Empresa XYZ',
      dataInicio: '2023-09-02',
      dataTermino: '2024-02-02',
    },
    {
      id: 10,
      tipo: 'Estágio',
      estagiario: 'Fernando Silva',
      departamento: 'Produção',
      status: 'Em andamento',
      concedente: 'Empresa 789',
      dataInicio: '2023-10-10',
      dataTermino: '2024-03-10',
    },
  ];
  
  export default data;
  